// Code generated by 'go generate'; DO NOT EDIT.

package mpr

import (
	"syscall"
	"unsafe"

	"golang.org/x/sys/windows"
)

var _ unsafe.Pointer

// Do the interface allocations only once for common
// Errno values.
const (
	errnoERROR_IO_PENDING = 997
)

var (
	errERROR_IO_PENDING error = syscall.Errno(errnoERROR_IO_PENDING)
	errERROR_EINVAL     error = syscall.EINVAL
)

// errnoErr returns common boxed Errno values, to prevent
// allocations at runtime.
func errnoErr(e syscall.Errno) error {
	switch e {
	case 0:
		return errERROR_EINVAL
	case errnoERROR_IO_PENDING:
		return errERROR_IO_PENDING
	}
	// TODO: add more here, after collecting data on the common
	// error values see on Windows. (perhaps when running
	// all.bat?)
	return e
}

var (
	modmpr = windows.NewLazySystemDLL("mpr.dll")

	procWNetGetUniversalNameW = modmpr.NewProc("WNetGetUniversalNameW")
)

func wNetGetUniversalNameW(lpLocalPath *uint16, dwInfoLevel uintptr, lpBuffer *_REMOTE_NAME_INFOW, lpBufferSize *uint32) (e error) {
	r0, _, _ := syscall.Syscall6(procWNetGetUniversalNameW.Addr(),
		4, uintptr(unsafe.Pointer(lpLocalPath)),
		uintptr(dwInfoLevel),
		uintptr(unsafe.Pointer(lpBuffer)),
		uintptr(unsafe.Pointer(lpBufferSize)),
		0, 0)
	if r0 != 0 {
		e = syscall.Errno(r0)
	}
	return
}
